# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  cloudProvider: {}
  environment: {}

annotations: {}
podAnnotations: {}

enabled: true
replicaCount: 1
environment: development
nodeSelector: {}
tolerations: []
affinity: {}

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: my-registry.io

image:
  repository: 'microcosm-cgimap'
  # Overrides the image tag whose default is the chart appVersion.
  #tag: 'v1'
  pullPolicy: Always

nginx:
  repository: nginx
  tag: 116

service:
  nodePort: 30100

resources:
  enabled: false
  value:
    limits:
      cpu: '2'
      memory: '2Gi'
    requests:
      cpu: '1'
      memory: '1Gi'

dbConfig:
  host: web-db
  username: postgres
  password: postgres
  database: openstreetmap
  port: 5432
  sslAuth:
    enabled: false
    secretName: secret-name

env:
  INSTANCES: 30
  CHANGESET_TIMEOUT_OPEN: "1 day"
  CHANGESET_TIMEOUT_IDLE: "1 day"
  MAX_CHANGESET_ELEMENTS: "50000"
  MAX_PAYLOAD: "5000000"
  MAX_WAY_NODES: "25000"
  RATELIMIT: "204800"
  MAXDEBT: "250"

probes:
  backend:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 30
      failureThreshold: 3
  proxy:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 10
      failureThreshold: 3

route:
  enabled: true
  path: /
  tls:
    termination: edge
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
