{{- $releaseName := .Release.Name -}}
{{- $chartName := include "openstreetmap-website.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-oauth-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "openstreetmap-website.environment" . }}
    release: {{ $releaseName }}
    {{- include "openstreetmap-website.labels" . | nindent 4 }}
type: Opaque
data:
  OAUTH_ID_KEY:  {{ .Values.env.oauthKey | b64enc }}
{{- end }}
