{{- $releaseName := .Release.Name -}}
{{- $chartName := include "openstreetmap-website.name" . -}}
{{- $cloudProviderFlavor := include "openstreetmap-website.cloudProviderFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "openstreetmap-website.environment" . }}
    release: {{ $releaseName }}
    {{- include "openstreetmap-website.labels" . | nindent 4 }}
spec:
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      {{- if eq $cloudProviderFlavor  "minikube" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "openstreetmap-website.selectorLabels" . | nindent 4 }}
{{- end }}
