{{- if and .Values.earthTiles.enabled .Values.earthTiles.pods.loader.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-earth-tiles-loader
  labels:
    app: {{ template "microcosm.name" . }}
    component: earth-tiles-loader-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "microcosm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-earth-tiles-loader
  template:
    metadata:
      labels:
        app: {{ template "microcosm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-earth-tiles-loader
    spec:
      containers:
        - name: {{ .Chart.Name }}-earth-tiles-loader
          {{- if eq .Values.cloudProvider.name "minikube" }} 
          image: {{ .Values.earthTiles.pods.loader.image.repository }}:{{ .Values.earthTiles.pods.loader.image.tag }}
          {{- else }}
          image: {{ .Values.cloudProvider.dockerRegisteryUrl }}/{{ .Values.earthTiles.pods.loader.image.repository }}:{{ .Values.earthTiles.pods.loader.image.tag }}
          {{- end }}
          {{- if .Values.earthTiles.pods.loader.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.earthTiles.pods.loader.resources.requests.memory }}
              cpu: {{ .Values.earthTiles.pods.loader.resources.requests.cpu }}
            limits:
              memory: {{ .Values.earthTiles.pods.loader.resources.limits.memory }}
              cpu: {{ .Values.earthTiles.pods.loader.resources.limits.cpu }}
          {{- end }}
          env:
            - name: LOAD_EXTERNAL_SCHEDULE_CRON
              value: {{ .Values.earthTiles.pods.loader.env.LOAD_EXTERNAL_SCHEDULE_CRON }}
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-configmap
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-configmap
                  key: database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-secret
                  key: username
            - name: OGR_ENABLE_PARTIAL_REPROJECTION
              value: 'true'
{{- end }}