{{- if and .Values.global.deployConfig .Values.earthTiles.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-earth-tiles-configmap
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "microcosm.name" . }}
    component: vector-tiles-earth-tiles-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.earthTiles.pods.db.enabled }}
  host: {{ .Release.Name }}-earth-tiles
  {{- else }}
  host: {{ .Values.earthTiles.dbConfig.host }}
  {{- end }}
  database: {{ .Values.earthTiles.dbConfig.db }}
{{- end }}