{{- if .Values.ingress.enabled -}}
{{- $fullName := include "microcosm.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "microcosm.name" . }}
    component: ingress
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          {{- if and .Values.vectorTiles.enabled .Values.vectorTiles.pods.tegola.enabled }}
          - path: /()({{ .Values.vectorTiles.pods.tegola.env.URI_PREFIX }}.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-tegola
                port: 
                  number: {{ .Values.vectorTiles.pods.tegola.env.TILER_SERVER_PORT }}
          {{- end }}
          {{- if and .Values.rasterizedTiles.enabled .Values.rasterizedTiles.pods.modTile.enabled }}
          - path: /tiles(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-mod-tile
                port: 
                  number: 80
          {{- end }}
          {{- if and .Values.ingestion.enabled .Values.ingestion.pods.web.enabled }}
          # We need the empty capture group 
          - path: "/()(.*)"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port: 
                  number: 80
          {{- end }}
{{- end }}
