{{- if and .Values.rasterizedTiles.enabled .Values.rasterizedTiles.pods.modTile.enabled -}}
{{- if .Values.rasterizedTiles.pods.modTile.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mod-tile-pv-claim
  labels:
    app: {{ template "microcosm.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.rasterizedTiles.pods.modTile.persistenceDisk.accessMode }}
  resources:
    requests:
      storage: {{ .Values.rasterizedTiles.pods.modTile.persistenceDisk.storageSize }}
{{- end }}
{{- end }}