{{- if and .Values.rasterizedTiles.enabled .Values.rasterizedTiles.pods.modTile.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mod-tile
  labels:
    app: {{ template "microcosm.name" . }}
    component: mod-tile-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  # In case cloudProvider=minikube
  {{- if eq .Values.cloudProvider.name  "minikube" }}
  type: NodePort
  {{- end }}
  
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      {{- if eq .Values.cloudProvider.name  "minikube" }}
      nodePort: {{ .Values.rasterizedTiles.pods.modTile.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "microcosm.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-mod-tile
{{- end }}