{{- if and .Values.rasterizedTiles.enabled .Values.rasterizedTiles.pods.osm2pgsql.enabled -}}
{{- if .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-osm2pgsql
  labels:
    app: {{ template "microcosm.name" . }}
    component: osm2pgsql
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-osm2pgsql
  replicas: 1
  serviceName: {{ .Release.Name }}-osm2pgsql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-osm2pgsql
    spec:
      containers:
      - name: {{ .Release.Name }}-osm2pgsql
        {{- if eq .Values.cloudProvider.name  "minikube" }} 
        image: {{ .Values.rasterizedTiles.pods.osm2pgsql.image.repository }}:{{ .Values.rasterizedTiles.pods.osm2pgsql.image.tag }}
        {{- else }}
        image: {{ .Values.cloudProvider.dockerRegisteryUrl }}/{{ .Values.rasterizedTiles.pods.osm2pgsql.image.repository }}:{{ .Values.rasterizedTiles.pods.osm2pgsql.image.tag }}
        {{- end }}
        {{- if .Values.rasterizedTiles.pods.osm2pgsql.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.rasterizedTiles.pods.osm2pgsql.resources.requests.memory }}
            cpu: {{ .Values.rasterizedTiles.pods.osm2pgsql.resources.requests.cpu }}
          limits:
            memory: {{ .Values.rasterizedTiles.pods.osm2pgsql.resources.limits.memory }}
            cpu: {{ .Values.rasterizedTiles.pods.osm2pgsql.resources.limits.cpu }}
        {{- end }}
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-rasterized-tiles-db-configmap
                key: host
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-rasterized-tiles-db-configmap
                key: database
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rasterized-tiles-db-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rasterized-tiles-db-secret
                key: username
          - name: POSTGRES_PORT
            value: {{ .Values.rasterizedTiles.dbConfig.port | default 5432 | quote }}
          - name: OSM2PGSQL_UPDATE_INTERVAL
            value: {{ quote .Values.rasterizedTiles.pods.osm2pgsql.env.UPDATE_INTERVAL }}
          - name: EXPIRED_DIR
            value: {{ .Values.rasterizedTiles.pods.osm2pgsql.env.EXPIRED_DIRECTORY }}
          - name: REPLICATION_URL
            value: http://{{ .Release.Name  }}-replication-http-server/minute
        volumeMounts:
        - mountPath: {{ .Values.rasterizedTiles.pods.osm2pgsql.env.EXPIRED_DIRECTORY }}
          name: osm2pgsql-expired-storage
      restartPolicy: Always
      volumes:
        - name: osm2pgsql-expired-storage
        {{- if .Values.rasterizedTiles.pods.osm2pgsql.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-osm2pgsql-expired-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
{{- end }}