{{- if and .Values.ingestion.enabled .Values.ingestion.pods.planetDump.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-planet-dump
  labels:
    app: {{ template "microcosm.name" . }}
    component: planet-dump
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "microcosm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-planet-dump
  template:
    metadata:
      labels:
        app: {{ template "microcosm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-planet-dump
    spec:
      containers:
      - name: {{ .Release.Name }}-planet-dump
        {{- if eq .Values.cloudProvider.name  "minikube" }} 
        image: {{ .Values.ingestion.pods.planetDump.image.repository }}:{{ .Values.ingestion.pods.planetDump.image.tag }}
        {{- else }}
        image: {{ .Values.cloudProvider.dockerRegisteryUrl }}/{{ .Values.ingestion.pods.planetDump.image.repository }}:{{ .Values.ingestion.pods.planetDump.image.tag }}
        {{- end }}
        {{- if .Values.ingestion.pods.planetDump.resources.enabled }}   
        resources:
          requests:
            memory: {{ .Values.ingestion.pods.planetDump.resources.requests.memory }}
            cpu: {{ .Values.ingestion.pods.planetDump.resources.requests.cpu }}
          limits:
            memory: {{ .Values.ingestion.pods.planetDump.resources.limits.memory }}
            cpu: {{ .Values.ingestion.pods.planetDump.resources.limits.cpu }}
        {{- end }}
        volumeMounts:
          - name: dump-storage
            mountPath: {{ .Values.ingestion.pods.planetDump.persistenceDisk.mountPath }}
        env:
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-web-configmap
                key: host
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-web-configmap
                key: database
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-web-secret
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-web-secret
                key: username
          - name: CREATE_DUMP_SCHEDULE_CRON
            value: {{ quote .Values.ingestion.pods.planetDump.env.CREATE_DUMP_SCHEDULE_CRON }}
          - name: DUMP_STORAGE_FOLDER
            value: {{ .Values.ingestion.pods.planetDump.persistenceDisk.mountPath }}
      volumes:
        - name: dump-storage
        {{- if .Values.replicationJob.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-planet-dump-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}
