{{- if and .Values.global.deployConfig .Values.rasterizedTiles.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rasterized-tiles-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "microcosm.name" . }}
    component: rasterized-tiles-db-secret
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username:  {{ .Values.rasterizedTiles.dbConfig.user | b64enc }}
  password: {{ .Values.rasterizedTiles.dbConfig.password | b64enc }}
{{- end }}