{{- $releaseName := .Release.Name -}}
{{- $name := include "microcosm.name" . -}}
{{- if  and .Values.ingestion.enabled .Values.ingestion.pods.replicationMerger.enabled -}}
{{- range .Values.ingestion.pods.replicationMerger.timeUnits }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-replication-merger-{{ .name }}
  labels:
    app: {{ $name }}
    component: replication-merger-{{ .name }}
    environment: {{ $.Values.environment }}
    release: {{ $releaseName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-replication-merger-{{ .name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-replication-merger-{{ .name }}
    spec:
      containers:
        - name: {{ $releaseName }}-replication-merger-{{ .name }}-deployment
          {{- if eq .Values.cloudProvider.name  "minikube" }} 
          image: {{ .Values.ingestion.pods.replicationMerger.image.repository }}:{{ .Values.ingestion.pods.replicationMerger.image.tag }}
          {{- else }}
          image: {{ .Values.cloudProvider.dockerRegisteryUrl }}/{{ .Values.ingestion.pods.replicationMerger.image.repository }}:{{ .Values.ingestion.pods.replicationMerger.image.tag }}
          {{- end }}
          {{- if $.Values.ingestion.pods.replicationMerger.resources.enabled }}
          resources:
            requests:
              memory: {{ $.Values.ingestion.pods.replicationMerger.resources.requests.memory }}
              cpu: {{ $.Values.ingestion.pods.replicationMerger.resources.requests.cpu }}
            limits:
              memory: {{ $.Values.ingestion.pods.replicationMerger.resources.limits.memory }}
              cpu: {{ $.Values.ingestion.pods.replicationMerger.resources.limits.cpu }}
          {{- end }}
          volumeMounts:
            - name: replication-storage
              mountPath: {{ $.Values.ingestion.pods.replicationMerger.persistenceDisk.mountPath }}/{{ .name }}
            - name: replication-config
              mountPath: /app/config
              readOnly: true
          env:
            - name: REPLICATION_MERGE_INTERVAL
              value: {{ quote .interval }}
            - name: TIME_UNIT_TO_MERGE
              value: {{ .name }}
            - name: TIME_UNIT_BASED_ON
              value: {{ .based_on }}
            - name: REPLICATION_URL
              value: http://{{ $releaseName }}-replication-http-server
            # In case cloudProvider=aws
            #{{- if eq $.Values.cloudProvider.name  "aws" }}
            #- name: AWS_S3_BUCKET
            #  value: {{ $.Values.AWS_S3_BUCKET }}
            #{{- end }}
              # Memory optimization for osmosis
            {{- if $.Values.ingestion.pods.replicationMerger.resources.enabled }}
            - name: MEMORY_JAVACMD_OPTIONS
              value: {{ $.Values.ingestion.pods.replicationMerger.resources.requests.memory | default "2Gi" | quote}}
            {{- end }}
      volumes:
        - name: replication-storage
        {{- if $.Values.ingestion.pods.replicationMerger.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ $releaseName }}-replication-merger-{{ .name }}-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: replication-config
          configMap:
            name: {{ $releaseName }}-replication-merger-configmap
---
{{- end -}}
{{- end -}}