{{- if and .Values.vectorTiles.enabled .Values.vectorTiles.pods.tegola.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-tegola
  labels:
    app: {{ template "microcosm.name" . }}
    component: tegola-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "microcosm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-tegola
  serviceName: {{ .Release.Name }}-tegola
  template:
    metadata:
      labels:
        app: {{ template "microcosm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-tegola
    spec:
      containers:
        - name: {{ .Chart.Name }}-tegola
          {{- if eq .Values.cloudProvider.name  "minikube" }} 
          image: {{ .Values.vectorTiles.pods.tegola.image.repository }}:{{ .Values.vectorTiles.pods.tegola.image.tag }}
          {{- else }}
          image: {{ .Values.cloudProvider.dockerRegisteryUrl }}/{{ .Values.vectorTiles.pods.tegola.image.repository }}:{{ .Values.vectorTiles.pods.tegola.image.tag }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.vectorTiles.pods.tegola.env.TILER_SERVER_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /mvt
              port: {{ .Values.vectorTiles.pods.tegola.env.TILER_SERVER_PORT }}
            initialDelaySeconds: 60 # 10 min, because the compile process takes time.
            timeoutSeconds: 30
          {{- if .Values.vectorTiles.pods.tegola.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.vectorTiles.pods.tegola.resources.requests.memory }}
              cpu: {{ .Values.vectorTiles.pods.tegola.resources.requests.cpu }}
            limits:
              memory: {{ .Values.vectorTiles.pods.tegola.resources.limits.memory }}
              cpu: {{ .Values.vectorTiles.pods.tegola.resources.limits.cpu }}
          {{- end }}
          env:
              # tiler-db env variables
            - name: OSM_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-configmap
                  key: host
            - name: OSM_POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-configmap
                  key: database
            - name: OSM_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-secret
                  key: password
            - name: OSM_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-vector-tiles-secret
                  key: username
            - name: EARTH_TILES_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-configmap
                  key: host
            - name: EARTH_TILES_POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-configmap
                  key: database
            - name: EARTH_TILES_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-secret
                  key: password
            - name: EARTH_TILES_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-earth-tiles-secret
                  key: username
            - name: URI_PREFIX
              value: /{{ .Values.vectorTiles.pods.tegola.env.URI_PREFIX }}
            - name: TILER_SERVER_PORT
              value: {{ .Values.vectorTiles.pods.tegola.env.TILER_SERVER_PORT | quote }}
            - name: TILER_CACHE_TYPE
              value: {{ .Values.vectorTiles.pods.tegola.env.TILER_CACHE_TYPE }}
            - name: TILER_CACHE_BUCKET
              value: {{ .Values.vectorTiles.pods.tegola.env.TILER_CACHE_BUCKET }}
            - name: TILER_CACHE_BASEPATH
              value: {{ quote .Values.vectorTiles.pods.tegola.env.TILER_CACHE_BASEPATH }}
            - name: TILER_CACHE_AWS_ACCESS_KEY_ID
              value: {{ quote .Values.vectorTiles.pods.tegola.env.TILER_CACHE_AWS_ACCESS_KEY_ID }}
            - name: TILER_CACHE_AWS_SECRET_ACCESS_KEY
              value: {{ quote .Values.vectorTiles.pods.tegola.env.TILER_CACHE_AWS_SECRET_ACCESS_KEY }}
            - name: TILER_CACHE_MAX_ZOOM
              value: {{ quote .Values.vectorTiles.pods.tegola.env.TILER_CACHE_MAX_ZOOM }}
            - name: TILER_CACHE_MIN_ZOOM
              value: {{ quote .Values.vectorTiles.pods.tegola.env.TILER_CACHE_MIN_ZOOM }}
            - name: EXPIRE_TILES_DIR
              value: {{ .Values.vectorTiles.pods.tegola.env.EXPIRE_TILES_DIR }}
            - name: TILER_CACHE_UPDATE_INTERVAL
              value: {{ quote .Values.vectorTiles.pods.tegola.env.TILER_CACHE_UPDATE_INTERVAL }}
          volumeMounts:
          - mountPath: /mnt/data
            name: tegola-storage
          - mountPath: {{ .Values.vectorTiles.pods.tegola.env.EXPIRE_TILES_DIR }}
            name: expired-tiles
      restartPolicy: Always
      volumes:
        - name: tegola-storage
        {{- if .Values.vectorTiles.pods.tegola.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tegola-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: expired-tiles
        {{- if .Values.vectorTiles.pods.imposm.persistenceDisk.expired.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-imposm-expired-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}