{{- if and .Values.global.deployConfig .Values.vectorTiles.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vector-tiles-configmap
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "microcosm.name" . }}
    component: vector-tiles-db-configmap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.vectorTiles.pods.db.enabled }}
  host: {{ .Release.Name }}-vector-tiles
  {{- else }}
  host:  {{ .Values.vectorTiles.dbConfig.host }}
  {{- end }}
  database: {{ .Values.vectorTiles.dbConfig.db }}
{{- end }}