{{- if .Values.ingestion.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  labels:
    app: {{ template "microcosm.name" . }}
    component: ingress
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
# {{- if .Values.ingress.tls }}
#   tls:
#   {{- range .Values.ingress.tls }}
#     - hosts:
#       {{- range .hosts }}
#         - {{ . }}
#       {{- end }}
#       secretName: {{ .secretName }}
#   {{- end }}
# {{- end }}
  rules:
    # - host: {{ .Values.ingestion.ingress.hostname }}
    - http:
        paths:
          - path: /api/0\.6/(way|relation)/[\d]+/full(\.(json|xml))?
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-cgimap
                port: 
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-web
                port: 
                  number: 80
{{- end }}
