{{- if and .Values.ingestion.enabled .Values.ingestion.pods.webDb.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-web-db
  labels:
    app: {{ template "microcosm.name" . }}
    component: web-db-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1 # we only ever want one replica of the db
  selector:
    matchLabels:
      app: {{ template "microcosm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-web-db
  serviceName: {{ .Release.Name }}-web-db
  template:
    metadata:
      labels:
        app: {{ template "microcosm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-web-db
    spec:
      containers:
        - name: {{ .Chart.Name }}-web-db
          {{- if eq .Values.cloudProvider.name  "minikube" }} 
          image: {{ .Values.ingestion.pods.webDb.image.repository }}:{{ .Values.ingestion.pods.webDb.image.tag }}
          {{- else }}
          image: {{ .Values.cloudProvider.dockerRegisteryUrl }}/{{ .Values.ingestion.pods.webDb.image.repository }}:{{ .Values.ingestion.pods.webDb.image.tag }}
          {{- end }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-web-configmap
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-web-configmap
                  key: database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-secret
                  key: username
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-web-secret
                  key: username
            - name: PGDATA
              value: {{ .Values.ingestion.pods.webDb.persistenceDisk.mountPath }}
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.ingestion.pods.webDb.persistenceDisk.mountPath }}
              subPath: {{ .Values.ingestion.pods.webDb.persistenceDisk.subPath }}
          {{- if .Values.ingestion.pods.webDb.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.ingestion.pods.webDb.resources.requests.memory }}
              cpu: {{ .Values.ingestion.pods.webDb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.ingestion.pods.webDb.resources.limits.memory }}
              cpu: {{ .Values.ingestion.pods.webDb.resources.limits.cpu }}
          {{- end }}
      volumes:
        - name: postgres-storage
        {{- if .Values.ingestion.pods.webDb.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-web-db-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- end }}