{{- $releaseName := .Release.Name -}}
{{- $chartName := include "cgimap.name" . -}}
{{- $cloudProviderFlavor := include "cgimap.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "cgimap.cloudProviderDockerRegistryUrl" . -}}
{{- $tag := include "cgimap.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "cgimap.environment" . }}
    release: {{ $releaseName }}
    {{- include "cgimap.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "cgimap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        environment: {{ include "cgimap.environment" . }}
        {{- include "cgimap.selectorLabels" . | nindent 8 }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-cgimap-backend
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .repository }}:{{ $tag }}
          {{- else }}
          image: {{ .repository }}:{{ $tag }}
          {{- end }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          command:
            - "/app/start.sh"
          args:
            - --port=8000
            - --instances=30
            - --changeset-timeout-open={{ .Values.env.CHANGESET_TIMEOUT_OPEN }}
            - --changeset-timeout-idle={{ .Values.env.CHANGESET_TIMEOUT_IDLE }}
            - --max-changeset-elements={{ .Values.env.MAX_CHANGESET_ELEMENTS }}
            - --max-payload={{ .Values.env.MAX_PAYLOAD }}
            - --max-way-nodes={{ .Values.env.MAX_WAY_NODES }}
            - --ratelimit={{ .Values.env.RATELIMIT }}
            - --maxdebt={{ .Values.env.MAXDEBT }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: {{ .Values.probes.backend.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.backend.readiness.periodSeconds }}
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: {{ .Values.probes.backend.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.backend.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.backend.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.backend.liveness.failureThreshold }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
            - secretRef:
                name: {{ $releaseName }}-{{ $chartName }}-secret
          {{ if .Values.dbConfig.sslAuth.enabled }}
          volumeMounts:
            - name: cert-conf
              mountPath: /tmp/certs
              readOnly: true
          {{ end }}
        - name: {{ $releaseName }}-{{ $chartName }}-cgimap-proxy
          {{- with .Values.nginx }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .repository }}:{{ .tag }}
          {{- else }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: {{ .Values.probes.proxy.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.proxy.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: {{ .Values.probes.proxy.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.proxy.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.proxy.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.proxy.liveness.failureThreshold }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-nginx-configmap
        {{ if .Values.dbConfig.sslAuth.enabled }}
        - name: cert-conf
          secret:
            secretName: {{ .Values.dbConfig.sslAuth.secretName }}
        {{ end }}
{{- end }}
