{{- $releaseName := .Release.Name -}}
{{- $chartName := include "cgimap.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-nginx-configmap
data:
  default.conf: |-
    server {
        server_name localhost;
        listen 8080;

        location = /status {
            stub_status;
        }

        location / {
            include /etc/nginx/fastcgi_params;
            fastcgi_pass 127.0.0.1:8000;
        }
    }

{{- end }}
