{{- $releaseName := .Release.Name -}}
{{- $chartName := include "cgimap.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "cgimap.environment" . }}
    release: {{ $releaseName }}
    {{- include "cgimap.labels" . | nindent 4 }}
type: Opaque
data:
  CGIMAP_USERNAME:  {{ .Values.dbConfig.username | b64enc }}
  CGIMAP_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
{{- end }}
